### ISSUE TITLE
Why doesn't this repo have 68k stars instead of 68?!

### ISSUE THREAD

**Issue by ma-sadeghi** [tengjuilin/markdown-resume#2]
Hi @tengjuilin, you've saved me countless number of hours! I have been switching back and forth between Word and LaTeX, every time refactoring some aspect only to realize it's not worth it, then switching to the other only to re-learn the quirks that originally made me switch, and it's been a broken cycle!

I don't know how to thank you enough :)

**Comment by tengjuilin** [comment]
Hi @ma-sadeghi, thanks so much for trying markdown-resume! I'm glad it's helpful to you - feel free to try it out and let me know if there's anything inconvenient in using it or any additional features needed. It can also be easily deployed to website as a static page ([example](https://tengjuilin.netlify.app/cv/cv_full/)). Feel free to spread the work and let more people trying it. Thanks!

**Comment by ma-sadeghi** [comment]
The only issue I had was page breaks. Ideally, they shouldn't happen right after `h2` and `h3` elements, also `h3` contents should ideally be kept together (if possible, i.e., not too long). I fixed it using some CSS rules, also made a PR (#3) to your repo in case you think that's a good addition.
